version: '3.1'
services:
  stuff-service:
    build: ./stuff
    ports:
      - 80:80
      - 3000:80
    environment:
      - TEST_VAL
      - TEST_VAL2
      - TEST
      - TEST1
      - TEST2
      - SQUASH_BRANCH_WITH_ID
      - SQUASH_DOMAIN
      - SQUASH_MASTER_DEPLOYMENT
      - ${SQUASH_BRANCH_WITH_ID}ABC
      - a42
    command: bash ./run_server.sh
    volumes:
      - /assets:/assets
